const map=L.map('map').setView([-4.325,15.31],12);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap contributors'}).addTo(map);
const list=document.querySelector('#salons-list');const locateButton=document.querySelector('#locate-button');
const status=document.querySelector('#location-status');
let userMarker;
const markers=new Map();
function toMinutes(t){const[h,m]=t.split(':').map(Number);
    return h*60+m}function getOpenStatus(salon){const now=new Date();
        const range=salon.hours[now.getDay()];
        if(!range)return{open:false,text:'Fermé aujourd’hui'};
        const current=now.getHours()*60+now.getMinutes();
        const start=toMinutes(range[0]),end=toMinutes(range[1]);
        return current>=start&&current<end?{open:true,text:`Ouvert jusqu’à ${range[1]}`}:{open:false,text:`Fermé · horaires ${range[0]}–${range[1]}`}}function haversine(lat1,lng1,lat2,lng2){const R=6371;
            const rad=v=>v*Math.PI/180;
            const dLat=rad(lat2-lat1),dLng=rad(lng2-lng1);
            const a=Math.sin(dLat/2)**2+Math.cos(rad(lat1))*Math.cos(rad(lat2))*Math.sin(dLng/2)**2;
            return R*2*Math.atan2(Math.sqrt(a),Math.sqrt(1-a))}function directions(salon){return `https://www.google.com/maps/dir/?api=1&destination=${salon.lat},${salon.lng}`}function card(salon,closest=false){const opening=getOpenStatus(salon);
                const distance=Number.isFinite(salon.distance)?`<p class="salon-meta">Distance approximative : ${salon.distance.toFixed(1)} km</p>`:'';return `<article class="salon-card ${closest?'closest':''}"><h3>${salon.name}</h3><p>${salon.address}</p>${distance}<p class="${opening.open?'open':'closed'}">${opening.text}</p><div class="actions"><a class="text-link" href="${directions(salon)}" target="_blank" rel="noopener">Itinéraire →</a><a class="text-link" href="reservation.html?salon=${salon.id}">Réserver →</a></div></article>`}function render(items=SALONS){list.innerHTML=items.map((salon,index)=>card(salon,index===0&&Number.isFinite(salon.distance))).join('')}SALONS.forEach(salon=>{const opening=getOpenStatus(salon);
                    const marker=L.marker([salon.lat,salon.lng]).addTo(map).bindPopup(`<strong>${salon.name}</strong><br>${salon.address}<br><span class="${opening.open?'open':'closed'}">${opening.text}</span>`);
                    markers.set(salon.id,marker)});
                    render();
                    locateButton.addEventListener('click',()=>{if(!navigator.geolocation){status.textContent='La géolocalisation n’est pas disponible sur cet appareil.';return}status.textContent='Recherche de votre position…';
                    navigator.geolocation.getCurrentPosition(position=>{const{latitude,longitude}=position.coords;
                        if(userMarker)userMarker.remove();
                        userMarker=L.marker([latitude,longitude]).addTo(map).bindPopup('Votre position').openPopup();
                        const sorted=SALONS.map(salon=>({...salon,distance:haversine(latitude,longitude,salon.lat,salon.lng)})).sort((a,b)=>a.distance-b.distance);
                        render(sorted);
                        map.fitBounds([[latitude,longitude],...SALONS.map(s=>[s.lat,s.lng])],{padding:[30,30]});
                        status.textContent=`Salon le plus proche : ${sorted[0].name} à environ ${sorted[0].distance.toFixed(1)} km.`;
                    },()=>{status.textContent='Position non disponible. Autorisez la localisation dans votre navigateur ou consultez la liste des salons.';

                    },{enableHighAccuracy:true,timeout:10000,maximumAge:60000});
                });
